# This variable is set by project() in CMake 3.21+
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
   set(IS_TOPLEVEL_PROJECT ON CACHE INTERNAL "" FORCE)
else()
   set(IS_TOPLEVEL_PROJECT OFF CACHE INTERNAL "" FORCE)
endif()

