name: clang

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    # Install Clang 15 using Homebrew
    - name: Install Clang 15
      run: |
        brew install llvm@15
        echo "/usr/local/opt/llvm@15/bin" >> $GITHUB_PATH

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} -j 2

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} -j 2 --output-on-failure