name: clang

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    # Install Clang 16 using Homebrew
    - name: Install Clang 16
      run: |
        brew install llvm@16
        echo "/usr/local/opt/llvm@16/bin" >> $GITHUB_PATH
        echo 'export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"' >> /Users/runner/.bash_profile
        export LDFLAGS="-L/opt/homebrew/opt/llvm@16/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm@16/include"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} -j 2

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} -j 2 --output-on-failure